version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  ipam:
    depends_on:
      - mysql
    image: pierrecdn/phpipam
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ENV_MYSQL_HOST=mysql
    ports:
      - "80:80"

  vault:
    image: vault
    container_name: dev-vault
    cap_add: 
      - IPC_LOCK
    ports:
      - "8200:8200"

  openldap:
    image: bitnami/openldap
    ports:
      - '0.0.0.0:1389:1389'
      - '0.0.0.0:1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=vault,netbox,phpipam
      - LDAP_PASSWORDS=password1,password2,password3
    volumes:
      - 'openldap_data:/bitnami/openldap'

  phpldapadmin:
    image: dinkel/phpldapadmin
    ports: 
      - "8201:80"
    depends_on: 
      - openldap
    environment: 
      - LDAP_SERVER_HOST=openldap
      - LDAP_SERVER_PORT=1389

volumes:
  db_data:
  openldap_data: